### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by Arbagen** [Arbagen/php_start#1]
@krestonos
прочитай про [docker](https://habrahabr.ru/post/309556/) и [docker-compose](https://habrahabr.ru/post/322440/) на хабре
поставь в убунту
читай внимательно, не все нужно копипастить в терминал. не понятно? [переводи](https://translate.google.com.ua/)
тут например команда для определенной версии
![img](http://img.netpeak.ua/dante/2017-12-17_a9b62f.png)
[docker install](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce)
выполни [пост шаги](https://docs.docker.com/engine/installation/linux/linux-postinstall/)
теперь [docker-compose](https://docs.docker.com/compose/install/#uninstallation)
склонируй эту репу , зайди в нее и запусти 
`docker-compose up --build`
в терменале должно быть 
![img](http://img.netpeak.ua/dante/2017-12-17_ec579c.png)
вкладку не закрывай, т.к. закроешь и контейнеры докера
(можно запустить в фонов решиме через 
`docker-compose up -d --build`, но не видно будет запросы в терменале)
зайди на [http://127.0.0.1:8080/](http://127.0.0.1:8080/) и проверь работает ли веб сервер и пхп
будет примерно ![img](http://img.netpeak.ua/dante/2017-12-17_15a091.png)

будут ошибки - гугли, не найдешь - пиши

**Comment by krestonos** [comment]
done

**Comment by krestonos** [comment]
docker-compose up --build //start containers
docker-compose exec php bash // drop in container
